# torchrun
# nproc_per_node: 2

### Logging in wandb
# switch to False to debug and run interactively
wandb_log: True


# data paths
static_root: "/work3/s220493/static"
bl_root: '../BL30K'
yv_root: '/work3/s220493/YouTube'
yv2018_root: '/work3/s220493/YouTube2018'
davis_root: '/work3/s220493/DAVIS'
coco_root: '/work3/s220493/coco'


# STCN
benchmark: True
no_amp: True
amp: False
stage: 2
single_object: False
steps: [250000]

# Training parameters
num_workers: 8
batch_size: 16 #8
iterations: 3000000 # corresponds to 2.5k epochs. Use the next entry to set the number of epochs
n_epochs: 1000
gamma: 0.1
lr: 0.00001




# Loading
load_network: null
load_model: null
id: 'NULL'

# to reduce the logging ot the out log file
debug: False
local-rank: 0

# Save models and netowrks path
save_model_path: '/work3/s220493/saves/'
exp_name: 'davis'

## Part of YoutubeVOS used
## float from 0 to 1
davis_part: 1
yt_vos_part: 0


######################################
## Validation and online validation ##
######################################
validation_step: True
online_validation: True
online_validation_steps: 5

### Augmentations
defaults:
    - augmentations: exp_multi_data