# Augmentation probability
augmentation_p: 0

# Tranformations for new mask params

# between 0.01 (small positive) and whatever
scale_factor_lower_lim: 0.5
scale_factor_upper_lim: 2

# Translation
translation_lim: 0.5 # half of height and width is the max to be added to the coords of each px

# Horizontal flip probability
horizontal_flip_p: 0.5


# Augmentation options
select_instances: False
foreground_p: 1.0
include_new_instances: False
